language: node_js
node_js:
  - "node" # Last current
  - "lts/*" # LTS
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
script:
  - npm run test:coverage-report-lcovonly
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - rm -rf ./coverage